default:
  image: registry.gitlab.com/smspp/smspp-project

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - smspp-project

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SMSPP_DEPLOY_KEY")
    - mkdir -p ~/.ssh && ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
    - if [ -d smspp-project ]; then (cd smspp-project && git pull); else git clone --branch develop --recurse-submodules git@gitlab.com:smspp/smspp-project.git; fi
    - cmake -S smspp-project -B smspp-project/build -DCMAKE_BUILD_TYPE=Release -DBUILD_tools=ON
    - cmake --build smspp-project/build --target install
  artifacts:
    paths:
      - smspp-project/build
  only:
    refs:
      - develop
      - tags
    changes:
      - cmake/*
      - CMakeLists.txt

deploy:
  stage: deploy
  script:
    - cd smspp-project/build && cpack -G "TGZ;ZIP;TBZ2"
  artifacts:
    paths:
      - smspp-project/build/*.tar.gz
      - smspp-project/build/*.tar.bz2
      - smspp-project/build/*.zip
  only:
    - tags
